# A Makefile for fusing Google Test and building a sample test against it.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make check  - makes everything and runs the built sample test.
#   make clean  - removes all files generated by make.

GTEST_DIR = ./test
GTEST_INCLUDE_DIR = $(GTEST_DIR)/include

# Flags passed to the preprocessor.
# We have no idea here whether pthreads is available in the system, so
# disable its use.
CPPFLAGS += -I$(GTEST_INCLUDE_DIR) -DGTEST_HAS_PTHREAD=0

# Flags passed to the C++ compiler.
CXXFLAGS += -g

test : $(GTEST_DIR)/rolitest
	$(GTEST_DIR)/rolitest

rolitest.o : $(GTEST_DIR)/rolitest.cpp $(GTEST_INCLUDE_DIR)/gtest.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GTEST_DIR)/rolitest.cpp -o $(GTEST_DIR)/$@

rolitest : $(GTEST_DIR)/gtest-all.o $(GTEST_DIR)/gtest_main.o $(GTEST_DIR)/rolitest.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $(GTEST_DIR)/$@
